In [35]:
from grid_world import GridWorld, Action
import numpy as np

In [36]:
gamma = 0.9
rows = 5
cols = 5

In [37]:
env = GridWorld(
    desc=[".....", ".##..", "..#..", ".#T#.", ".#..."],
    forbidden_score=-10,
    terminal_score=1,
)
print("init grid:")
env.render_grid()
# print("init policy:")
state_values = np.zeros(rows * cols)
q_table = np.zeros((rows * cols, len(Action)))
# policy = np.argmax(q_table, axis=1)
# env.render_policy(policy)

print("random policy:")
# policy = np.random.choice(len(Action), size=rows * cols)
policy = np.eye(cols)[np.random.randint(0, 5, size=(rows * cols))]
env.render_policy(policy)

init grid:
⬜️⬜️⬜️⬜️⬜️
⬜️🚫🚫⬜️⬜️
⬜️⬜️🚫⬜️⬜️
⬜️🚫✅🚫⬜️
⬜️🚫⬜️⬜️⬜️
random policy:
⬆️➡️⬅️➡️⬆️
➡️⏫️⏫️⬆️🔄
⬇️➡️⏫️⬆️⬆️
➡️⏫️✅⏬⬅️
⬆️⏬⬇️⬅️⬇️


In [40]:
max_iters = 1000
theta = 1e-3
traj_steps = 100
old_q_table = q_table.copy() + 1

for iter in range(max_iters):

    delta = np.sum((old_q_table - q_table) ** 2)
    print(f"iter {iter} Euclidean Distance:{delta}")

    old_q_table= q_table.copy()
    for state in range(env.get_state_space_size()):
        for action in range(env.get_action_space_size()):
            # [state, action, reward, next_state, next_action] in each element
            traj = env.get_traj(state, action, policy, steps=traj_steps)

            reward = traj[-1][2]
            for k in range(traj_steps - 1, -1, -1):
                reward = reward * gamma + traj[k][2]
            q_table[state][action] = reward

    print(f"q_table:\n{q_table[17]}")
    print(f"{q_table[22]}")
    policy = np.eye(cols)[np.argmax(q_table, axis=1)]
    env.render_policy(policy)

    if delta < theta:
        print(f"Converged at iteration {iter}")
        break


iter 0 Euclidean Distance:125.0
q_table:
[-99.99760947 -99.99760947   0.         -99.99760947   9.99976095]
[  9.99976095   0.          -9.99976095 -99.99760947   0.        ]
➡️➡️➡️➡️⬇️
⬆️⏫️⏫️⬆️⬆️
⬆️⬅️⏬⬆️⬆️
⬆️⏩️✅⏪⬆️
⬆️⏩️⬆️➡️⬆️
iter 1 Euclidean Distance:292486.0155906381
q_table:
[-99.99760947 -99.99760947   0.         -99.99760947   9.99976095]
[  9.99976095   0.          -9.99976095 -99.99760947   0.        ]
➡️➡️➡️➡️⬇️
⬆️⏫️⏫️⬆️⬆️
⬆️⬅️⏬⬆️⬆️
⬆️⏩️✅⏪⬆️
⬆️⏩️⬆️➡️⬆️
iter 2 Euclidean Distance:0.0
q_table:
[-99.99760947 -99.99760947   0.         -99.99760947   9.99976095]
[  9.99976095   0.          -9.99976095 -99.99760947   0.        ]
➡️➡️➡️➡️⬇️
⬆️⏫️⏫️⬆️⬆️
⬆️⬅️⏬⬆️⬆️
⬆️⏩️✅⏪⬆️
⬆️⏩️⬆️➡️⬆️
Converged at iteration 2
